version: '3'
services:
  server:
    container_name: grocery-store-server
    hostname: grocery-store-server
    domainname: grocery-store-server
    restart: always
    build: ./server/
    command: bash -c "yarn global add babel-cli -S; yarn; yarn start"
    env_file: ./server/.env
    volumes:
      - .:/app:cached
    ports:
      - "4000:4000"
    networks: 
      - grocery-store-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.nextjs
    container_name: grocery-store-fe
    # env_file: .env
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - "$PWD:/frontend"
    networks: 
      - grocery-store-network

  # nginx:
  #   restart: always
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.nginx
  #   container_name: mini-waffles-nginx
  #   ports:
  #     - 80:9090
  #     - 443:9090
  #   networks: 
  #     - grocery-store-network

  redis:
    image: redis:latest
    command: redis-server --loglevel warning --requirepass redisPass
    container_name: grocery-store-cache
    hostname:       grocery-store-cache
    domainname:     grocery-store-cache
    ports:
      - "6379:6379"
    networks: 
      - grocery-store-network

  postgres:
    image: postgres:10.5
    container_name: grocery-store-db
    restart: always
    environment:
      - POSTGRES_USER=grocery_store
      - POSTGRES_PASSWORD=grocery-store-123
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
    networks: 
      - grocery-store-network

  minio:
    image: docker.io/bitnami/minio:2022
    container_name: grocery-store-bucket
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - grocery-store-network
    volumes:
      - ./minio_data:/data
    environment:
      - MINIO_ROOT_USER=grocery_store
      - MINIO_ROOT_PASSWORD=grocery-store-123
      - MINIO_DEFAULT_BUCKETS=grocery-store-bucket

networks:
  grocery-store-network:
    driver: "bridge"
  minio_data:
    driver: local
